### ISSUE TITLE
QBEC, Qbec or qbec?

### ISSUE THREAD

**Issue by kvaps** [splunk/qbec#113]
Hi @gotwarlost,

I'm writing new article about the qbec (https://github.com/kubernetes/website/pull/18630), and I want to know what is correct writing for it's name?

**Comment by gotwarlost** [comment]
qbec

**Comment by kvaps** [comment]
Post is published on Medium:
https://medium.com/@kvaps/trying-new-tools-for-building-and-automate-the-deployment-in-kubernetes-f96f9684e580
