### ISSUE TITLE
Some plural names don't work with qbec filters

### ISSUE THREAD

**Issue by harsimranmaan** [splunk/qbec#144]
eg:
`kubectl get storageclass` and `kubectl get storageclasses` show the StorageClasses in a clusters.

`qbec  show envName -k StorageClasses` does not work but `qbec  show envName -k StorageClass` works fine.

**Comment by harsimranmaan** [comment]
Looks like this can be addressed by replacing https://github.com/splunk/qbec/blob/master/internal/model/filter.go#L89-L96 with PluralNamer from the k8s project https://github.com/kubernetes/gengo/blob/master/namer/plural_namer_test.go#L25

**Comment by gotwarlost** [comment]
https://qbec.io/userguide/usage/commands/#kind-filters
