### ISSUE TITLE
feature requiest: resolveDockerImage function

### ISSUE THREAD

**Issue by kvaps** [splunk/qbec#18]
It would be nice for add an option to resolve docker images to `sha256` tag:

Example proposal:
```
{
   image: std.resolveDockerImage('ubuntu:18.04'),
}
```
will be translated to:
```
{
  image: 'docker.io/library/ubuntu@sha256:017eef0b616011647b269b5c65826e2e2ebddbe5d1f8c1e56b3599fb14fabec8',
}
```

Or we can use external handler, eg skopeio:
```
  skopeo inspect docker://docker.io/ubuntu:18.04
```

**Comment by gotwarlost** [comment]
sorry for the delay in response. I've some concerns in implementing functionality like this that provides different outputs for the same inputs over time. 

Quoting `dcunnin` from the Kubernetes jsonnet slack:

> you can register native functions that can do whatever you want, but you have to use jsonnet as a library
> however those functions have to be reproducable or the behavior is undefined
so fetching from an immutable or append-only store is OK
> writing is definitely not OK
> reading the current time or the latest version is not ok
> a better way of doing it is sometimes to fetch before you even run Jsonnet and have it as an input to the whole config elaboration. That means you can store the result of the fetch for audit / replay purposes or just for debugging
> but obviously you can't do that if you need jsonnet to compute the parameters of the fetch

and `guslees`

>The main thing is to be repeatable.  So you probably want to aggressively cache any remote operations that might-but-probably-won't change result.  For example, kubecfg supports `import` from URLs, but it caches it (in memory) and won't actually fetch the same URL twice.  The assumption of course is that people use it for immutable URL content, and not dynamic content.

Also in this particular case you probably want to resolve it once in your dev build and then use the results to promote to prod environments. resolving dynamically for a prod build means that you might deploy something untested to production.

Let me know what you think.

**Comment by kvaps** [comment]
Great idea! Now I understand why ksonnet moved this functionality from the native function to `ks param set --resolve-image` option
BTW I even thought to place this functionality on Kubernetes side, but small script which is reading params and just generates jsonnet file with the image digests should be enough.
I like this idea, because digests can also be stored in the git.

Currently I'm in a vacation, I'll write here afterwards when I find a solution.

**Comment by Andor** [comment]
@kvaps I guess you don't even need to generate jsonnet file, you can specify your sha256 sums with external variables: https://qbec.io/userguide/usage/runtime-params/#using-jsonnet-external-variables

**Comment by gotwarlost** [comment]
closing this as "won't fix"
