### ISSUE TITLE
don't try to GC default namespace

### ISSUE THREAD

**Issue by gotwarlost** [splunk/qbec#2]
If someone accidentally declares the `default` namespace as one of the objects in a component and later removes it, `qbec` will try and delete it and fail, since k8s doesn't allow deleting the default namespace.

**Comment by gotwarlost** [comment]
or `kube-system` for that matter

**Comment by evanmcclure** [comment]
I'm working on this.

**Comment by gotwarlost** [comment]
fixed in v0.10 with standard processing attached to delete policy. Sorry, @evanmcclure - this got pre-empted by the policy feature :)
