### ISSUE TITLE
0.14.0 includes backwards incompatible jsonnet change

### ISSUE THREAD

**Issue by splkforrest** [splunk/qbec#226]
We have some jsonnet that looks similar to this:
```
local foo = [{bar: 'baz'}];
std.manifestJsonEx(foo, ' ')
```
which works fine using Jsonnet v0.17.0. However, upgrading to the latest qbec (v0.14.0) introduces a dependency on an incompatible jsonnet version that breaks this. Rather than manifesting into JSON we get
```
Error: RUNTIME ERROR: Unexpected type array, expected object
```
There is a work around to wrap the array in an object, but it would be nice to not have to do that.

**Comment by gotwarlost** [comment]
fix in v0.14.1
