### ISSUE TITLE
0.14.0 changed the behavior for setting the working directory

### ISSUE THREAD

**Issue by mattk42** [splunk/qbec#228]
Prior to 0.14.0 qbec would set the working directory automatically to the deploy:

```
# qbec_0.13.7 apply local --vm:ext-str-list secret-vars.txt
cd /path/to/deploy
```

after upgrading to 0.14.X that behavior seems to have gone away:
```
# qbec_0.14.0 apply local --vm:ext-str-list secret-vars.txt
✘ open secret-vars.txt: no such file or directory
```

**Comment by gotwarlost** [comment]
This regression slipped past me in major refactor of simplifying the abec initialization code.

This is actually consistent with how we access environment files - relative to the current directory before processing the root.

Unfortunately for various reasons, this is very hard to fix in a way that provides 100% backwards-compat so I'll update the release notes with this breakage as well. Sorry for the undocumented regression.
