### ISSUE TITLE
feature requiest: allow nested environments

### ISSUE THREAD

**Issue by kvaps** [splunk/qbec#23]
Hi,

Ksonnet was support to create nested environments eg. `us-west/staging` where `us-west/staging` inherits parameters from `us-west` it would be nice to add this opportunity to qbec also.

Thank you!

**Comment by gotwarlost** [comment]
Unlike `ksonnet`, `qbec` doesn't really care how you produce runtime parameters which is totally up to the user who is given a `qbec.io/env` variable to work with. You  could totally implement this hierarchical structure yourself if you wanted to.

**Comment by kvaps** [comment]
Yes, but you can't use `/` in the names

**Comment by gotwarlost** [comment]
That is true. Since the environment name is used as a k8s label, it can't have slashes in it. Unless we do some name mangling - I'm not very inclined to do this

**Comment by kvaps** [comment]
Ok, agree, it's not so important, environments can be described with dash instead slash when it's needed separation, eg:

```
us-west/staging
us-west/prod
```
can be written as

```
us-west-staging
us-west-prod
```

with inheritance from `us-west`
