### ISSUE TITLE
Don't show usage help output when there's an actual error to report.

### ISSUE THREAD

**Issue by leesplk** [splunk/qbec#235]
for example if i do `qbec show <env>...`  and provide a syntactically valid qbec command, but i'm not a directory with a qbec.yaml file, i get: 
```
Usage:
  qbec show <environment> [flags] 
... 10 more lines of irrelevant noise

✘ unable to find source root at or above
```
Nothing in the usage message is relevant in this situation, it just distracts from the actual error message.  My assumption when i see that message is theres a syntax error in my command line, which

**Comment by gotwarlost** [comment]
is this a "for example" bug report which indicates many other places where this happens? Or is this the only one?

**Comment by gotwarlost** [comment]
usually the usage message is only printed for usage errors

**Comment by gotwarlost** [comment]
Fixed via https://github.com/splunk/qbec/commit/dea9e7c5af2ea15a9d03e6e3149b586cb67d3d94
