### ISSUE TITLE
Docs site needs to be published to uptake changes

### ISSUE THREAD

**Issue by nickshine** [splunk/qbec#281]
<img width="210" alt="Screen Shot 2022-02-15 at 9 43 27 AM" src="https://user-images.githubusercontent.com/3190044/154097183-20473f1c-c094-40bd-b121-5177c7149c94.png">

The "Edit this page" links on https://qbec.io are broken because they still reference `master` branch and that has been renamed to `main`.

The `editURL` config setting [looks to be updated](https://github.com/splunk/qbec/blob/main/site/config.yaml#L11) so I am guessing `publish-docs.sh` just needs to be ran?

**Comment by gotwarlost** [comment]
done
