### ISSUE TITLE
Integrate qbec repo with the CLA assistant

### ISSUE THREAD

**Issue by harsimranmaan** [splunk/qbec#293]
https://github.com/splunk/cla-agreement

**Comment by gotwarlost** [comment]
I was going to ask you to send a PR but then I realized what that would mean... :)

**Comment by harsimranmaan** [comment]
ha, yeah. There seems to be no obvious/discoverable option on how to sign the CLA or what the CLA is. The agreement bot seems to be the most viable.

**Comment by gotwarlost** [comment]
I set up something but not tested. could you send some real or dummy MR so we can see what happens?

**Comment by harsimranmaan** [comment]
It's failing
```
CLA Assistant GitHub Action bot has started the process
Error: Could not retrieve repository contents: Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.. Status: 403
Error: Cannot read property 'data' of undefined
```

**Comment by taitken-splunk** [comment]
I have finally fixed this now.
