### ISSUE TITLE
Provide way to customize jpath in config and/or with environment variables.

### ISSUE THREAD

**Issue by Andor** [splunk/qbec#30]
In case of use qbec in conjunction with `jsonnet-bundler` it is handy to have a feature to set `--vm:jpath` in the config file and/or environment variable.

Otherwise, I should always specify it in the command line like this:
```
$ qbec --vm:jpath ./vendor/ apply infra
```

**Comment by gotwarlost** [comment]
I think `libPaths` is what you are looking for. Re-open the issue if it didn't answer your question.

https://qbec.io/reference/qbec-yaml/

**Comment by Andor** [comment]
@gotwarlost Oh, thank you! This is exactly what I wanted and somehow miss it in the documentation.
