### ISSUE TITLE
Allow passing variables via TLA

### ISSUE THREAD

**Issue by splkfinn** [splunk/qbec#4]
Per [The Jsonnet Tutorial](https://jsonnet.org/learning/tutorial.html#parameterize-entire-config), there are two ways to pass in external variables: external variables and top level arguments (TLAs). Unfortunately, qbec doesn't work with TLAs:

```
qbec show --vm:tla-str "image=xxxxx" -v 10 play1
Eval components:
local parseYaml = std.native('parseYaml');
local parseJson = std.native('parseJson');
{
  'gatewayrouter': import 'components/gatewayrouter.jsonnet'
}
✘ evaluate components: RUNTIME ERROR: couldn't manifest function in JSON output.
	During manifestation	
```

per our discussion on Slack, the import statement is generated by qbec itself, and cannot be changed to import it and call it as a function.

I would like a mechanism to allow me to use TLAs in qbec

**Comment by gotwarlost** [comment]
could you explain what is the use-case you are trying to achieve and what are the blockers with not using TLAs? Perhaps we could solve the underlying problem without TLAs (which, gut feel says, might be hard to support)

**Comment by splkfinn** [comment]
It's not possible to check if an external variable exists before accessing it, and attempts to access non-existent external variables cause an error, which there doesn't seem to be a way to catch.

I can work around this by restructuring the code works and requiring all possible variables be passed in every time we run qbec, but that's suboptimal and it would be nice to not have to do it.

**Comment by gotwarlost** [comment]
This actually turned out to be a good idea. See #5

**Comment by gotwarlost** [comment]
@splkfinn could you pull down the `tla` branch and verify that the changes actually solve the problem you set out to solve?

**Comment by gotwarlost** [comment]
as discussed the TLA approach doesn't work well because passing in a TLA when a component doesn't require it is not allowed.
