### ISSUE TITLE
devise a framework for per-object tweaking of qbec behavior

### ISSUE THREAD

**Issue by gotwarlost** [splunk/qbec#56]
The known use case today is to be able to control GC of transient objects like jobs and one-off pods. 

The approach would likely for the user to declare qbec-namespaced annotations for objects that qbec can then respect. 

Continue to document additional cases where this may be required in this ticket.

**Comment by gotwarlost** [comment]
The second case is a `wait` case where we might want to wait for jobs. However, there are 2 valid ways in which the wait can be done.

* Wait for the pod associated to a job to be ready
* Wait for the job itself to run to completion

In this case, we could implement a default behavior and allow the user to pick the other one via an annotation on the object

**Comment by gotwarlost** [comment]
see #69 for some detailed use cases

**Comment by gotwarlost** [comment]
Proposal: Reserve the "annotation namespace" `directives.qbec.io`  to mean "things I want to tell qbec to customize its behavior".

Implement the following directives:

* `directives.qbec.io/update-policy: default|never` - `default` means "as needed", `never` means "do not update ever"

* `directives.qbec.io/gc-policy: default|never` - `default` means "as needed",  `never` means do not garbage collect _and_ do not delete even with an explicit `qbec delete` command. 

When qbec discovers that an object should not be deleted, it will automatically _compute_ the delete policy of the associated namespace object if one exists as `never` (it won't actually update any annotations on the namespace object)

TODO: add more policies from original use cases here.

@kvaps - let me know if this sounds good

**Comment by kvaps** [comment]
Awesome! I like this change 🙂

**Comment by gotwarlost** [comment]
implemented in v0.10
