### ISSUE TITLE
qbec show should be able to generate kubectl applyable output

### ISSUE THREAD

**Issue by Andor** [splunk/qbec#60]
Right now (`0.7.5`) `qbec show` generate output with two issues:
1. dos newlines;
2. qbec-related data at the beginning and at the end of the output.
```
$ qbec show --colors=false infra -S -c grafana > stuff.yaml

$ file stuff.yaml
stuff.yaml: ASCII text, with very long lines, stuff.yaml: ASCII text, with very long lines, with CRLF line terminators

$ head -3 stuff.yaml 
1 components evaluated in 415ms
---
apiVersion: v1

$ tail -3 stuff.yaml
  namespace: default

command took 420ms

```

**Comment by gotwarlost** [comment]
What os are you running on?

**Comment by gotwarlost** [comment]
```
  qbec show -c basic -k namespace dev1 | kubectl --context dev1 apply -f -
1 components evaluated in 48ms
namespace/monitoring unchanged
```

The above command, run on Mac OS tells me that the output of `qbec show` is compatible with `kubectl apply -f -`

It looks like when you are running commands, stdout and stderr are intermixed in the output

**Comment by Andor** [comment]
I run `qbec` in docker container under Linux.
Maybe the simpler "fix" for this issue is just to make an explicit flag to disable any non-yaml output?

**Comment by gotwarlost** [comment]
non-yaml output is already on a separate stream and I consider that to be working. 

It's unfortunate that `docker run` doesn't distinguish between stdout and stderr.

Let me research this some more and get back to you. This page seems to indicate that separating stdout and stderr is possible if you don't ask docker for a TTY: 

https://forums.docker.com/t/docker-exec-how-to-separate-stderr-and-stdout/40405/3

See if that works for you

**Comment by gotwarlost** [comment]
also the "dos newlines" problem may be because of the same reason

**Comment by Andor** [comment]
```
docker run -i --rm -w /srv --volume $(pwd):/srv -t --volume /home/andor/.config/gcloud:/home/andor/.config/gcloud --volume /home/andor/.kube:/home/andor/.kube eu.gcr.io/myproject-public/tools:latest qbec show --colors=false infra -S -c grafana
```
This is my exact command. As you can see, there are `-i` and `-t` flags present.

**Comment by gotwarlost** [comment]
That’s the problem. You need to remove -t to prevent docker from allocating a tty

**Comment by Andor** [comment]
Well, if I will run `qbec` without `-t` then I will not be able to put `y` in `Do you want to continue [y/n]:` so it's not the best solution just to remove `-t`.

**Comment by harsimranmaan** [comment]
You can use the --yes flag to suppress that prompt.

**Comment by gotwarlost** [comment]
there is also an environment variable called `QBEC_YES` that can be set to `"true"` in the docker container which will suppress the prompts. The solution is to run the container with this env var turned on and not use `-t` in the docker run command. 

I consider what is happening now (different streams for objects and messages) to be correct.
