### ISSUE TITLE
github release flow is not filename-compatible with what was happening before

### ISSUE THREAD

**Issue by gotwarlost** [splunk/qbec#89]
File names changed from `qbec-<plat>-<arch>.tar.gz` to `qbec_<version>_<plat>_<arch>.tar.gz` (`.zip` for windows) 

Note introduction of `version` and underscores instead of dashes.

Checksum file name changed from `sha256-checksums.txt` to `checksums.txt` and refers to new-style file names.

Can both of these be fixed with appropriate options to goreleaser? Otherwise, we are making downloads of qbec dependent on version number of its release.

I have manually fixed the above issues for `v0.9.0`

**Comment by gotwarlost** [comment]
@harsimranmaan could you take a look? Is it possible to fix this easily?

**Comment by gotwarlost** [comment]
Also, need a couple of other less important changes:

* Tag the output as a pre-release so I can do a manual step of updating the changelog to my liking and flipping the bit.
* Bonus: do not generate changelog from commits but pull it out of `CHANGELOG.md`, documenting the assumptions made in the extraction. If this is doable, the first point is moot.

**Comment by harsimranmaan** [comment]
will take a look later today
