### ISSUE TITLE
Figure out code coverage for qbec

### ISSUE THREAD

**Issue by gotwarlost** [splunk/qbec#97]
As in:

* Code coverage is computed for master as well as PRs
* Code coverage up/ down percent when a PR is submitted
* Bonus: a way to have detailed code coverage reports clickable from PR/ master

**Comment by gotwarlost** [comment]
@harsimranmaan - any ideas? Would you be willing to spend some time to make this happen?

**Comment by harsimranmaan** [comment]
I'll take a look this week
